[package]
name = "crab-o-clock"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.7", features = ["csr"] }
console_error_panic_hook = "0.1"
chrono = { version = "0.4", features = ["wasmbind"] }

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1